development:
  graphite_url: "http://graphite_example_url"

  ganglia_url: "http://ganglia_example_url"
  ganglia_host: "ganglia_example_hostname"

  sensu_url: "http://sensu_example_url"

  uptime_url: "http://uptime_example_url"

  jira_url: "http://jira_example_url" # e.g. "http://your-jira-installation/rest/api/latest/search"
  jira_user: "jira_example_user"
  jira_password: "jira_example_password"

  pingdom_user: "pingdom_example_user"
  pingdom_password: "pingdom_example_password"
  pingdom_api_key: "pingdom_exampe_api_key"

  new_relic_api_key: "new_relic_exampe_api_key"

test:

production:
  graphite_url: <%= ENV['GRAPHITE_URL'] %>

  ganglia_url: <%= ENV['GANGLIA_WEB_URL'] %>
  ganglia_host: <%= ENV['GANGLIA_HOST'] %>

  sensu_url: <%= ENV['SENSU_EVENTS_URL'] %>

  uptime_url: <%= ENV['UPTIME_URL']  %>

  jira_url: <%= ENV['JIRA_URL'] %> # e.g. "http://your-jira-installation/rest/api/latest/search"
  jira_user: <%= ENV['JIRA_USER'] %>
  jira_password: <%= ENV['JIRA_PASSWORD'] %>

  pingdom_user: <%= ENV['PINGDOM_USER'] %>
  pingdom_password: <%= ENV['PINGDOM_PASSWORD'] %>
  pingdom_api_key: <%= ENV['PINGDOM_API_KEY'] %>

  new_relic_api_key: <%= ENV['NEW_RELIC_API_KEY'] %>
